sudo: false
language: minimal

addons:
  apt:
    packages:
    - luarocks
    - liblua5.1-bitop0

branches:
  only:
  - master

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luaunit 2.1
  - luarocks install --local mockagne 1.0

script:
  - luac -p $(find . -name "*.lua")
  - lua ./tests/tests.lua

notifications:
  email:
    on_failure: always
