language: c
sudo: required
dist: trusty

env:
  - LUA="lua5.1" LUAC="luac5.1"

branches:
  only:
    - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y $LUA luarocks
  - sudo luarocks install luaunit
  - sudo luarocks install mockagne
  - sudo luarocks install luabitop

script:
  - $LUAC -p $(find . -name "*.lua")
  - cd tests
  - $LUA tests.lua

notifications:
  email:
    on_failure: always
    on_success: change
