sudo: false

env:
    - LUA="lua5.1" LUAC="luac5.1"

addons:
    apt:
        packages:
            - lua5.1
            - luarocks
            - liblua5.1-bitop0

branches:
    only:
        - master

install:
    - eval $(luarocks path --bin)
    - luarocks install --local luaunit 2.1
    - luarocks install --local mockagne 1.0
    - luarocks install --local luacheck

script:
    - $LUAC -p $(find . -name "*.lua")
    - cd tests
    - $LUA tests.lua

notifications:
    email:
        on_failure: always
